### PR TITLE
categories component

### PR DESCRIPTION
**Pull request by kimbencinas**
categories section for products page complete & made responsive

### CODE REVIEW

**Review by missile720 — APPROVED** [review]
Looks good! Other than the deprecated icon it is responsive.

**Review by AlissonRoss — CHANGES_REQUESTED** [review]
Scrolling up and down does not work while the menu is open which is strange.
Using Firefox on MacOS.

**Comment by missile720** [comment]
> Scrolling up and down does not work while the menu is open which is strange. Using Firefox on MacOS.

That is because when the menu is open the focus switches to the menu. I don't think this is a bug or issue.

**Review by AlissonRoss — APPROVED** [review]
Great job

**Pull request merged**
