### PR TITLE
fix(bug): Fixed the issue with the height for the shopping cart page …

### LINKED ISSUE #4: bug/body-height
image
- Fix Body Height so it does not resize and takes up the entire screen

### PR DESCRIPTION
**Pull request by missile720**
…and also fixed the logo img not showing

## Changes
_List Changes Introduced by this PR_
1. Fixed the height issue with the shopping cart
2. Fixed the issue with the image not loading
3. Removed unused folder

## Purpose
Now the height does not change visually when removing and adding items to cart. Logo is now visible

## Approach
Users can now see the logo and the page seems static in terms of the background

## Learning
N/A

_If this closes an issue, reference the issue here. If it doesn't, remove this line_
Closes #4

### CODE REVIEW

**Comment by kimbencinas** [comment]
Screenshot 2024-08-13 at 4 06 21 PM
seems like there's an error with the image

**Comment by missile720** [comment]
> Screenshot 2024-08-13 at 4 06 21 PM seems like there's an error with the image

I fixed it. The issue is coming from the navbar.js file within the components folder. I don't see this file being used anywhere.

**Review by AlissonRoss — CHANGES_REQUESTED** [review]
image
Icon is not inline with the header: You can set a Style that is like
```position: absolute;```
```top: 0; ```

to the img tag. You may also need to resize the image or make the white background transparent through photoshop or an app.
image
Seems like the icon is gone on the product list. Also, the icon does not persist and disappears when moving to the products page. I am using Firefox on MacOS

**Comment by missile720** [comment]
I fixed the issues
Capture4

**Review by kimbencinas — APPROVED** [review]

**Review by AlissonRoss — CHANGES_REQUESTED** [review]
Screenshot 2024-08-14 at 1 54 54 PM
Might want to change this to className instead.
Other than that, the image does load. However, it pushes the header or adds extra padding. You can play around with it but that's not necessarily an issue per say
image

**Comment by jm2601** [comment]
The categories drop down doesn't filter out products based on their category. The merge from dev to your branch may be missing some things. Try `git pull` on `dev`.

**Comment by missile720** [comment]
> The categories drop down doesn't filter out products based on their category. The merge from dev to your branch may be missing some things. Try `git pull` on `dev`.

The filter for the categories was never implemented I believe. My branch was merged with the dev branch

**Review by AlissonRoss — APPROVED** [review]
nice

**Review by jm2601 — APPROVED** [review]

**Pull request merged**
